const clubData = [
    {
      id: "1",
      title: "LAMU",
      category: "봉사분과",
      img: "",
      desc: "해비타트(CCYP)에 소속된 봉사 동아리",
    },
    {
        id: "2",
        title: "KUSA",
        category: "봉사분과",
        img: "",
        desc: "UNESCO 관련 활동 진행, 전국 60여개 학교의 KUSA 연합 활동 봉사 동아리",
    },
    {
        id: "3",
        title: "MUV",
        category: "봉사분과",
        img: "",
        desc: "집수리 봉사 동아리",
    },
    {
        id: "4",
        title: "스카우트",
        category: "봉사분과",
        img: "",
        desc: "봉사 캠핑 동아리",
    },
    {
        id: "5",
        title: "아이사랑",
        category: "봉사분과",
        img: "",
        desc: "탁아 봉사 동아리",
    },
    {
        id: "6",
        title: "포토랩",
        category: "평면예술분과",
        img: "",
        desc: "사진 찍는 것과 다같이 즐겁게 노는 것을 즐기는 동아리",
    },
    {
        id: "7",
        title: "A&P",
        category: "평면예술분과",
        img: "",
        desc: "천문 사진 동아리",
    },
    {
        id: "8",
        title: "필름아트",
        category: "평면예술분과",
        img: "",
        desc: "영화 감상 동아리",
    },
    {
        id: "9",
        title: "표현의 자유",
        category: "평면예술분과",
        img: "",
        desc: "그림과 글로 상상을 엮는 동아리",
    },
    {
        id: "10",
        title: "페가수스",
        category: "연행예술분과",
        img: "",
        desc: "밴드 동아리",
    },
    {
        id: "11",
        title: "우리또래",
        category: "연행예술분과",
        img: "",
        desc: "장르, 실력 상관없이 음악을 즐기는 동아리",
    },
    {
        id: "12",
        title: "소울메이트",
        category: "연행예술분과",
        img: "",
        desc: "힙합/R&B를 즐기는 동아리",
    },
    {
        id: "13",
        title: "CDC",
        category: "연행예술분과",
        img: "",
        desc: "춤에 열정이 가득한 동아리",
    },
    {
        id: "14",
        title: "이따위",
        category: "연행예술분과",
        img: "",
        desc: "하드/메탈 장르 밴드 동아리",
    },
    {
        id: "15",
        title: "CEMO",
        category: "연행예술분과",
        img: "",
        desc: "연극 동아리",
    },
    {
        id: "16",
        title: "울림소리",
        category: "연행예술분과",
        img: "",
        desc: "공연, 합주, 버스킹을 하는 전통 깊은 밴드 동아리",
    },
    {
        id: "17",
        title: "마라톤",
        category: "연행예술분과",
        img: "",
        desc: "밴드 동아리",
    },
    {
        id: "18",
        title: "예현회",
        category: "연행예술분과",
        img: "",
        desc: "클래식 기타 동아리",
    },
    {
        id: "19",
        title: "RATS",
        category: "과학분과",
        img: "",
        desc: "프로그래밍, 회로, CAD를 알려주는 로봇 동아리",
    },
    {
        id: "20",
        title: "i2pm",
        category: "과학분과",
        img: "",
        desc: "프로그래밍 언어 튜터링 및 스터디를 진행하는 동아리",
    },
    {
        id: "21",
        title: "M.C.C",
        category: "과학분과",
        img: "",
        desc: "하드웨어, 소프트웨어 설계를 모두 경험할 수 있는 동아리",
    },
    {
        id: "22",
        title: "슬기터",
        category: "과학분과",
        img: "",
        desc: "발명 창업 동아리",
    },
    {
        id: "23",
        title: "CAM 대학선교회",
        category: "종교분과",
        img: "",
        desc: "전국 40여 대학에서 활동하는 연합 기독교 동아리",
    },
    {
        id: "24",
        title: "CCC",
        category: "종교분과",
        img: "",
        desc: "한국 대학생 선교회 동아리",
    },
    {
        id: "25",
        title: "실로암",
        category: "종교분과",
        img: "",
        desc: "자생 기독교 동아리",
    },
    {
        id: "26",
        title: "CFM",
        category: "종교분과",
        img: "",
        desc: "수화 찬양 동아리",
    },
    {
        id: "27",
        title: "TIME",
        category: "인문사회분과",
        img: "",
        desc: "1979년부터 활동해온 영자 신문/잡지 동아리",
    },
    {
        id: "28",
        title: "수아브",
        category: "스포츠레저분과",
        img: "",
        desc: "주짓수 동아리",
    },
    {
        id: "29",
        title: "에임스팟",
        category: "스포츠레저분과",
        img: "",
        desc: "볼링 동아리",
    },
    {
        id: "30",
        title: "밸런스",
        category: "스포츠레저분과",
        img: "",
        desc: "배구 동아리",
    },
    {
        id: "31",
        title: "MEGA",
        category: "스포츠레저분과",
        img: "",
        desc: "교내 e-스포츠 대회 및 이벤트를 진행하는 게임 동아리",
    },
    {
        id: "32",
        title: "검심",
        category: "스포츠레저분과",
        img: "",
        desc: "체력을 기르고 스트레스를 푸는 검도 동아리",
    },
    {
        id: "33",
        title: "퍼펙트",
        category: "스포츠레저분과",
        img: "",
        desc: "야구 동아리",
    },
    {
        id: "34",
        title: "유니콘스",
        category: "스포츠레저분과",
        img: "",
        desc: "축구 동아리",
    },
    {
        id: "35",
        title: "M.T.C",
        category: "스포츠레저분과",
        img: "",
        desc: "테니스 동아리",
    },
    {
        id: "36",
        title: "배드신",
        category: "스포츠레저분과",
        img: "",
        desc: "배드민턴 동아리",
    },
    {
        id: "37",
        title: "SWISH",
        category: "스포츠레저분과",
        img: "",
        desc: "인문 캠퍼스와 교류전을 진행하는 농구 동아리",
    },
  ];
   
  export default clubData;